# Generated by Django 4.0.4 on 2022-04-19 07:41

import GamesPlay.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_max_level_alter_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=1, validators=[GamesPlay.core.validators.rating_validator]),
            preserve_default=False,
        ),
    ]
