# Generated by Django 4.0.4 on 2022-04-19 08:24

import GamesPlay.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_level',
            field=models.IntegerField(blank=True, validators=[GamesPlay.core.validators.max_level_validator]),
        ),
    ]
