# Generated by Django 4.0.4 on 2022-04-19 07:41

import GamesPlay.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[GamesPlay.core.validators.age_validator]),
        ),
    ]
