# Generated by Django 4.0.3 on 2022-03-30 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petstagramuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='date_joined',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
