# Generated by Django 3.1.3 on 2022-03-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pythons_auth', '0003_auto_20220325_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='profiles')),
                ('profile_description', models.CharField(max_length=200)),
                ('profile_website', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pythons_auth.pythonuser')),
            ],
        ),
    ]
